FROM mcr.microsoft.com/dotnet/sdk:10 AS build
WORKDIR /App

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore

RUN dotnet test -c Release

# Build and publish a release
RUN dotnet publish -o out -c Release
